version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
  movie-app: # Your Spring Boot Service
    image: movie-sb-app
    container_name: movie-app
    ports:
      - "8085:8083"
    build:
      context: ./backend/movie
    environment:
      # CRITICAL: Point to the service name 'elasticsearch' instead of localhost
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
  nginx-server-svc:
    image: my-react-nginx-server
    container_name: my-react-nginx
    ports:
      - "8080:80"
    build:
      context: ./nginx-server
    volumes:
      - ./nginx-server/my-nginx-conf:/etc/nginx/conf.d:ro
      - ./nginx-server/data:/usr/share/nginx/html:ro
  react-nginx-svc:
    image: react-movie-app
    container_name: react-movie-app
    ports:
      - "8086:8086"
    build:
      context: ./react-app-files

volumes:
  esdata:
